name: Testing in CI
on:
  push:
    branches:
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3.10.5-management
        ports:
          - 15672:15672
          - 5672:5672
      order-service:
        image: rolandstech/order
        ports:
          - 8083:8083
      notification-service:
        image: rolandstech/notification-service
        ports:
          - 8082:8082
    steps:
      - name: Cache ctags binary
        id: ctags-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/ctags
          key: ctags-${{ runner.os }}-${{ hashFiles('**/ctags-cache-key.txt') }}
      - name: Download ctags
        if: steps.ctags-cache.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/universal-ctags/ctags.git
          cd ctags
          ./autogen.sh
          ./configure
          make
          sudo make install
      - name: Print ctag version
        run: ctags --version
      - name: Get Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
#      - name: Check what was installed
#        run: ls -la
#      - name: Get Commit IDs
#        run: git log -n 5 --pretty=oneline
#      - name: Get Commit ID
#        run: git log -n 5 --pretty=oneline | head -n2 | tail -n1 | cut -d' ' -f1
#      - name: Get Changes
#        run: git diff "0ab1d21e0dc4e9bfa4925348dfea81dd7469774a" --name-only | grep -v "~"
#      - name: Run all tests
#        run: mvn clean test
      - name: Run tests
        run: |
          chmod +x get_hierarchy_classes.sh
          chmod +x get_dependency_tree.sh
          chmod +x run_tests.sh
          ./run_tests.sh

